"""
Pre-built demo scenarios.

Each scenario is a real submission drawn from the 22,000-row book, verified to
land on its stated outcome when scored through the live path (models + rules
engine). They are ordinary inputs: nothing here bypasses or pre-computes the
scoring, so a scenario runs exactly like a hand-typed submission.

Calibrated against real rows on purpose. Hand-invented input combinations
proved unreliable, they can sit outside the distribution the models were
trained on and land somewhere other than the label claims.
"""
from __future__ import annotations

# Default submission, also what the Reset button restores.
BASE = {
    "driver_age": 54,
    "years_licensed": 22,
    "annual_mileage": 6393,
    "vehicle_use": "Pleasure",
    "territory_type": "Suburban",
    "traffic_congestion": 10,
    "vehicle_theft_risk": 7,
    "coverage_lapse_days": 30,
    "undeclared_business_use": False,
    "prior_claims_3y": 0,
    "at_fault_claims_3y": 0,
    "prior_claims_5y": 0,
    "moving_violations_3y": 0,
    "speeding_violations_3y": 0,
    "major_violation": False,
    "dui_flag": False,
    "license_suspension": False,
    "telematics_enrolled": True,
    "telematics_safety_score": 70,
    "vehicle_value": 21800,
    "repairability_score": 9,
    "parts_cost_index": 0.97,
    "labor_cost_index": 0.8,
    "medical_cost_index": 1.37,
    "litigation_environment": 8,
    "luxury_vehicle": False,
    "performance_vehicle": False,
    "collision_deductible": 250,
    "comprehensive_deductible": 500,
    "cat_exposure_score": 2,
    "state_in_appetite": True,
    "prior_total_loss": False,
    "confirmed_fraud": False,
    "new_renewal": "New Business",
    "customer_tenure_years": 0,
    "multi_policy": False,
    "submission_channel": "Direct",
    "state": "NY",
    "agent_engagement": 20,
    "digital_engagement": 65,
    "quote_revisions": 1,
    "price_sensitivity": "Medium",
    "coverage_type": "Full Coverage (Comprehensive + Collision)",
    "competitor_premium_estimate": 0,
    "prior_year_premium": 900,
    "target_margin_pct": 5,
    "anti_theft_available": False,
    "body_type": "Sedan",
}


SCENARIOS = {
    'Clean preferred risk': {
        "blurb": 'Experienced low-mileage driver, no claims or violations, telematics enrolled. Straight-through quote with no underwriter touch.',
        "expect": 'Preferred / Auto-Quote',
        "inputs": {
            "driver_age": 54,
            "years_licensed": 22,
            "annual_mileage": 6393,
            "vehicle_use": "Pleasure",
            "territory_type": "Suburban",
            "traffic_congestion": 10,
            "vehicle_theft_risk": 7,
            "coverage_lapse_days": 30,
            "undeclared_business_use": False,
            "prior_claims_3y": 0,
            "at_fault_claims_3y": 0,
            "prior_claims_5y": 0,
            "moving_violations_3y": 0,
            "speeding_violations_3y": 0,
            "major_violation": False,
            "dui_flag": False,
            "license_suspension": False,
            "telematics_enrolled": True,
            "telematics_safety_score": 70,
            "vehicle_value": 21800,
            "repairability_score": 9,
            "parts_cost_index": 0.97,
            "labor_cost_index": 0.8,
            "medical_cost_index": 1.37,
            "litigation_environment": 8,
            "luxury_vehicle": False,
            "performance_vehicle": False,
            "collision_deductible": 250,
            "comprehensive_deductible": 500,
            "cat_exposure_score": 2,
            "state_in_appetite": True,
            "prior_total_loss": False,
            "confirmed_fraud": False,
            "new_renewal": "New Business",
            "customer_tenure_years": 0,
            "multi_policy": False,
            "submission_channel": "Direct",
            "state": "NY",
            "agent_engagement": 20,
            "digital_engagement": 65,
            "quote_revisions": 1,
            "price_sensitivity": "Medium",
            "coverage_type": "Full Coverage (Comprehensive + Collision)",
            "competitor_premium_estimate": 0,
            "prior_year_premium": 900,
            "target_margin_pct": 5,
            "anti_theft_available": False,
            "body_type": "Sedan",
},
    },
    'Standard risk, light review': {
        "blurb": 'Long-tenured driver with one prior claim. Acceptable, but routed for a light underwriter check rather than auto-quoted.',
        "expect": 'Standard / Light Review',
        "inputs": {
            "driver_age": 80,
            "years_licensed": 54,
            "annual_mileage": 10567,
            "vehicle_use": "Commute",
            "territory_type": "Suburban",
            "traffic_congestion": 6,
            "vehicle_theft_risk": 4,
            "coverage_lapse_days": 0,
            "undeclared_business_use": False,
            "prior_claims_3y": 1,
            "at_fault_claims_3y": 1,
            "prior_claims_5y": 1,
            "moving_violations_3y": 0,
            "speeding_violations_3y": 0,
            "major_violation": False,
            "dui_flag": False,
            "license_suspension": False,
            "telematics_enrolled": True,
            "telematics_safety_score": 65,
            "vehicle_value": 36500,
            "repairability_score": 8,
            "parts_cost_index": 0.91,
            "labor_cost_index": 0.94,
            "medical_cost_index": 1.05,
            "litigation_environment": 7,
            "luxury_vehicle": False,
            "performance_vehicle": False,
            "collision_deductible": 500,
            "comprehensive_deductible": 500,
            "cat_exposure_score": 2,
            "state_in_appetite": True,
            "prior_total_loss": False,
            "confirmed_fraud": False,
            "new_renewal": "New Business",
            "customer_tenure_years": 0,
            "multi_policy": False,
            "submission_channel": "Aggregator",
            "state": "PA",
            "agent_engagement": 1,
            "digital_engagement": 66,
            "quote_revisions": 0,
            "price_sensitivity": "High",
            "coverage_type": "Full Coverage (Comprehensive + Collision)",
            "competitor_premium_estimate": 0,
            "prior_year_premium": 900,
            "target_margin_pct": 5,
            "anti_theft_available": False,
            "body_type": "Sedan",
},
    },
    'Falls below appetite': {
        "blurb": 'No violations, but the loss-cost profile scores out of appetite. Shows the suggestions engine offering alternatives to a flat decline.',
        "expect": 'Decline, with alternatives',
        "inputs": {
            "driver_age": 77,
            "years_licensed": 37,
            "annual_mileage": 14879,
            "vehicle_use": "Commute",
            "territory_type": "Urban",
            "traffic_congestion": 6,
            "vehicle_theft_risk": 5,
            "coverage_lapse_days": 0,
            "undeclared_business_use": False,
            "prior_claims_3y": 0,
            "at_fault_claims_3y": 0,
            "prior_claims_5y": 0,
            "moving_violations_3y": 0,
            "speeding_violations_3y": 0,
            "major_violation": False,
            "dui_flag": False,
            "license_suspension": False,
            "telematics_enrolled": False,
            "telematics_safety_score": 75,
            "vehicle_value": 32300,
            "repairability_score": 9,
            "parts_cost_index": 0.88,
            "labor_cost_index": 0.89,
            "medical_cost_index": 1.02,
            "litigation_environment": 6,
            "luxury_vehicle": False,
            "performance_vehicle": False,
            "collision_deductible": 500,
            "comprehensive_deductible": 1000,
            "cat_exposure_score": 4,
            "state_in_appetite": True,
            "prior_total_loss": False,
            "confirmed_fraud": False,
            "new_renewal": "Renewal",
            "customer_tenure_years": 5,
            "multi_policy": True,
            "submission_channel": "Direct",
            "state": "GA",
            "agent_engagement": 22,
            "digital_engagement": 53,
            "quote_revisions": 0,
            "price_sensitivity": "Medium",
            "coverage_type": "Full Coverage (Comprehensive + Collision)",
            "competitor_premium_estimate": 0,
            "prior_year_premium": 1343,
            "target_margin_pct": 5,
            "anti_theft_available": False,
            "body_type": "Sedan",
},
    },
    'Undeclared business use': {
        "blurb": "Hard-stops on misrepresentation, but it's a negotiable one. Reclassifying to declared business use resolves it.",
        "expect": 'Hard Stop, negotiable',
        "inputs": {
            "driver_age": 66,
            "years_licensed": 18,
            "annual_mileage": 12963,
            "vehicle_use": "Commute",
            "territory_type": "Suburban",
            "traffic_congestion": 5,
            "vehicle_theft_risk": 6,
            "coverage_lapse_days": 0,
            "undeclared_business_use": True,
            "prior_claims_3y": 0,
            "at_fault_claims_3y": 0,
            "prior_claims_5y": 0,
            "moving_violations_3y": 0,
            "speeding_violations_3y": 0,
            "major_violation": False,
            "dui_flag": False,
            "license_suspension": False,
            "telematics_enrolled": False,
            "telematics_safety_score": 75,
            "vehicle_value": 6900,
            "repairability_score": 8,
            "parts_cost_index": 0.9,
            "labor_cost_index": 0.92,
            "medical_cost_index": 1.15,
            "litigation_environment": 3,
            "luxury_vehicle": False,
            "performance_vehicle": False,
            "collision_deductible": 0,
            "comprehensive_deductible": 250,
            "cat_exposure_score": 1,
            "state_in_appetite": True,
            "prior_total_loss": False,
            "confirmed_fraud": False,
            "new_renewal": "Renewal",
            "customer_tenure_years": 14,
            "multi_policy": True,
            "submission_channel": "Direct",
            "state": "MI",
            "agent_engagement": 34,
            "digital_engagement": 98,
            "quote_revisions": 0,
            "price_sensitivity": "Medium",
            "coverage_type": "Full Coverage (Comprehensive + Collision)",
            "competitor_premium_estimate": 0,
            "prior_year_premium": 1150,
            "target_margin_pct": 5,
            "anti_theft_available": False,
            "body_type": "Sedan",
},
    },
    'DUI on record': {
        "blurb": 'The one category with no underwriting discretion. Shows the app refusing to invent an alternative.',
        "expect": 'Mandatory decline',
        "inputs": {
            "driver_age": 24,
            "years_licensed": 5,
            "annual_mileage": 12604,
            "vehicle_use": "Pleasure",
            "territory_type": "Suburban",
            "traffic_congestion": 6,
            "vehicle_theft_risk": 5,
            "coverage_lapse_days": 0,
            "undeclared_business_use": False,
            "prior_claims_3y": 0,
            "at_fault_claims_3y": 0,
            "prior_claims_5y": 0,
            "moving_violations_3y": 1,
            "speeding_violations_3y": 1,
            "major_violation": False,
            "dui_flag": True,
            "license_suspension": False,
            "telematics_enrolled": False,
            "telematics_safety_score": 75,
            "vehicle_value": 18900,
            "repairability_score": 8,
            "parts_cost_index": 0.94,
            "labor_cost_index": 1.11,
            "medical_cost_index": 0.96,
            "litigation_environment": 6,
            "luxury_vehicle": False,
            "performance_vehicle": False,
            "collision_deductible": 0,
            "comprehensive_deductible": 0,
            "cat_exposure_score": 3,
            "state_in_appetite": True,
            "prior_total_loss": False,
            "confirmed_fraud": False,
            "new_renewal": "Renewal",
            "customer_tenure_years": 3,
            "multi_policy": False,
            "submission_channel": "Direct",
            "state": "TN",
            "agent_engagement": 15,
            "digital_engagement": 43,
            "quote_revisions": 0,
            "price_sensitivity": "Low",
            "coverage_type": "Full Coverage (Comprehensive + Collision)",
            "competitor_premium_estimate": 0,
            "prior_year_premium": 985,
            "target_margin_pct": 5,
            "anti_theft_available": False,
            "body_type": "Sedan",
},
    },
}

SCENARIO_NAMES = list(SCENARIOS.keys())
